server:
  port: 8001

spring:
  application:
    name: gateway8001
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        register: false
    gateway:
      # 开启动态路由
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: fun-provider
          uri: lb://fun-provider
          predicates:
            - Path=/**

